<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSQjacXA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSQjacXA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSQjacXA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSQjacXA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSQjacXA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SQjacXA',
    'container.build_id' => 'a4248913',
    'container.build_time' => 1652446964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSQjacXA');
